### ISSUE TITLE
Deployment Plan

### ISSUE THREAD

**Issue by anandology** [pipalacademy/train-ride#5]
I'm thinking it may be simpler and faster to deploy it ourselves on our own server rather than deploying to external services. That would also improve the deploy time considerably. 

## The Goal

Serve multiple webapps from a single server with very few resource usage and easy way to update it. Each webapp will run on a subdomain and will have its own code.

We may also have to support multiple databases for each site. It may be good enough to support sqlite for now.

## Tha Plan

Assume that each webapp will have a wsgi.py, exposing the a wsgi function with name `app`.

Setup a Apache+CGI setup that would invoke a python script for every request. The python script will look at the hostname and decides which directory to serve, adds that directory to `sys.path`, imports the `app` from `wsgi` and calls it with `environ` and `start_response`.

To make things simple, we can package the Apache+CGI and the python script as a docker image and mount the root directory with all apps into it. 

## Notes

Shall we create a new repo for this? This seems like a generic tool. @nikochiko what do you think?

**Comment by nikochiko** [comment]
This is done. https://github.com/pipalacademy/boring-serverless
Maybe, we can set a Docker for this in the future, so that the deployment process is cut down.
