### ISSUE TITLE
Turn the From and To stations in the form to autocomplete

### ISSUE THREAD

**Issue by anandology** [pipalacademy/train-ride#6]
On the home page, make the _From_ and _To_ station form elements into autocomplete. 

It should use the `/api/stations?q=xxx` endpoint to find the stations. 

The response format:

```
[
    {"code": "SBC", "name": "Bangalore"},
    {"code": "MAS", "name": "Chennai"},
]
```

The autocomplete should show the data as:

```
Bangalore  - SBC
Chennai - MAS
```

and later when the form is submitted, use only the code.

**Comment by nikochiko** [comment]
UI added in https://github.com/pipalacademy/train-ride/commit/033e62bddf4d2c762441deef18b209ba9f7d46ca
